### ISSUE TITLE
"failed to create process" on Windows

### ISSUE THREAD

**Issue by Javacym** [hhatto/autopep8#226]
when i type autopep8 or something autopep8 xx.py ,then,i call 'failed to create process.' this's why?
I first use this,tks(python version is 3.5)

**Comment by myint** [comment]
I think we will need more information than that. Please see the following link.

https://github.com/hhatto/autopep8/blob/master/CONTRIBUTING.rst#issues

**Comment by Javacym** [comment]
run autopep8 --version   failed to create process

**Comment by myint** [comment]
Sorry, but that just is not enough information. At least provide what the following commands output. Please copy and paste the results from the whole session.

```
autopep8 --version
which autopep8
pep8 --version
python --version
which python
uname -a
```

**Comment by Javacym** [comment]
so i means this package only work in linux-like system?
autopep8 --version  result:failed to create process.
which autopep8
pep8 --version result:1.6.2
which pep8
python --version  result:Python 3.5.0
which python
uname -a

**Comment by myint** [comment]
As far as I know, it works fine on Windows (which I'm guessing you are using).

In any case, I don't think this problem is caused by your installation rather than autopep8 itself. Please see the following links.

[https://duckduckgo.com/?q=!stackoverflow+"failed to create process"
](https://duckduckgo.com/?q=!stackoverflow+"failed to create process")
https://stackoverflow.com/questions/27627492/autopep8-failing-with-failed-to-create-process
https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process

**Comment by Javacym** [comment]
Thanks a lot!!!  I change this file C:\Program Files\Python 3.5\Scripts\autopep8-script.py 
before
#! c:\program files\python 3.5\python.exe
after
#! "c:\program files\python 3.5\python.exe"
then i work ,but  i do not know why

**Comment by TarasRoshko** [comment]
I don't quite understand why the issue was closed, It seems like a bug, steps to repro:

* Install latest `Python 3.x (x64)` for `Windows` using regular installer into default location (`C:\Program Files\Python35`
* Install `autopep8` using `pip`

`autopep8` is broken and won't start because it's missing quotes in `"C:\Program Files\Python35\Scripts\autopep8-script.py"` on line 1 which is:

`#!c:\program files\python35\python.exe`

So If you have `python` installed in the location with spaces (which is _the default_ for Windows Installer), `autopep8` won't start

**Comment by myint** [comment]
@TarasRoshko is this a `autopep8`-specific issue or is the problem due to `pip`? For example, if you install `pep8` using `pip`, does the resulting `pep8` executable work okay?

**Comment by TarasRoshko** [comment]
@myint Just did a clean repro to double check:

* Set up clean Windows VM (`2012 R2`, but this should not make any difference)
* Downloaded official `Python` installer for `x64`
* Installed specifying `For All Users` (checking this sets `Python` installation dir to `C:\Program Files\Python35`)
* `pip install pep8`
```
C:\Users\localadmin>pep8 --version
1.7.0
```

* `pip install --upgrade autopep8`
```
C:\Users\localadmin>autopep8 --version
failed to create process.
```
```
C:\Users\localadmin>pep8 --version
1.7.0
```

So it seems to be `autopep8` related (not handling paths with spaces)

**Comment by myint** [comment]
One difference in `pep8` is that it uploads wheels to PyPI. I've done the same here. Please try doing the `pip install` again.

**Comment by zcy921716** [comment]
Yes I still have this issues at the moment when I want to use python-autopep8 or auto-beauty plugin on atom. I used pip to install the autopep8 and then failed to use it whatever directly using in command window or with plugins. Then I added the " " issue was solved. I think it should be a bug needed to repair it which related to autopep8

**Comment by linrongbin16** [comment]
I solved my "failed to create process" issue ! Here's the explanation and solution.

I uninstalled and reinstalled python 3.7.2 on different location on my windows 10. First is `C:\Python37`, and I installed autopep8 with administrator `pip install autopep8`. 

The autopep8 we got is in `%USERPROFILE%\AppData\Roaming\Python\Python37\Scripts`, In this folder I found `autopep8-script.py` first line is:

```
#!c:\python37\python.exe
```

After I uninstalled and reinstalled python37 in `C:\data\Python37`, I also reinstalled autopep8 with `pip install autopep8` with administrator. The pip already found **the old autopep8** and skipped installation.

So finally I got this error:

```
failed to create process
```

Since autopep8-script.py cannot find the right position of **new** python.

So I removed whole directory `%USERPROFILE%\AppData\Roaming\Python` and reinstalled with pip, everything runs well again !
