### ISSUE TITLE
Support for E722

### ISSUE THREAD

**Issue by ghost** [hhatto/autopep8#297]
By replacing bare `except:` with `except Exception:`.

**Comment by hhatto** [comment]
support fix e722 with aggressive option.

**Comment by evhub** [comment]
@hhatto `except:` and `except Exception:` are not equivalent, and having `autopep8` change one into to other has the potential to cause some serious issues, like raising errors that should be caught. I just ran into some such errors caused by this change myself. I would suggest changing `except:` into `except BaseException:` instead, since those are in fact equivalent.

**Comment by hhatto** [comment]
@evhub 

Thanks for feedback.
That's right. I should have used BaseException.

fix in latest master.
