### ISSUE TITLE
add #noqa support for any line

### ISSUE THREAD

**Issue by matiasg** [hhatto/autopep8#307]
Sorry if it has been discussed before.

There's support for #noqa comments but it is restricted to lines in comments AFAICT.
It would be great to be able to exclude some lines from formatting also inside "real" code.

**Comment by ealfie** [comment]
:+1:

**Comment by hhatto** [comment]
refs: https://github.com/hhatto/autopep8/issues/223#issuecomment-153044749

> I think it is dependent on what pep8 supports. pep8 supports noqa for some error codes, I think.

I am also in this policy.

http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
> (^) These checks can be disabled at the line level using the # noqa special comment. This possibility should be reserved for special cases.

**Comment by Integralist** [comment]
Hmm, I recently discovered this doesn't work for me...

The following code will still get changed to use `isinstance` 🤔 

```py
if type(self._formatter) == LogFormatter:  # noqa
```

**Comment by qshzh** [comment]
same issue

**Comment by jackmoody11** [comment]
Also doesn't work for this:

```python
func = lambda x: x  # noqa
```

which it turns to 

```python
def func(x): return x  # noqa
```

**Comment by hhatto** [comment]
https://github.com/hhatto/autopep8/issues/307#issuecomment-662357341

@Integralist @qshzh 
This is because we are using lib2to3, which is unable to recognize line-level noqa.
We are in the process of developing version 2.0 and will switch from lib2to3 to our own implementation using LibCST.
Maybe this will improve the situation, but it will basically be parsed at the file-level, not at the line-level, so it may work the same as it did when we used lib2to3.


https://github.com/hhatto/autopep8/issues/307#issuecomment-768682525
Same reason as below.
It may be supported by autopep8 side in version 2.0 or later.
see: https://github.com/hhatto/autopep8/issues/527#issuecomment-607103558

**Comment by Borda** [comment]
@hhatto removing from 2.0 milestone means it won't be implemented? :rabbit:
