### ISSUE TITLE
Atom Beautify not working because not finding autopep8.

### ISSUE THREAD

**Issue by bramvana** [hhatto/autopep8#363]
![autopep8](https://user-images.githubusercontent.com/24454138/33529222-ffe0a464-d86d-11e7-88ba-29a01c0a2e36.png)

Followed instruction in error, went and did this: pip install --upgrade autopep8
Some autopep8 files ended up here:
C:\Users\MyNameHere\AppData\Local\Programs\Python\Python36-32\Scripts

Python (which has the pip command) installs itself in:
C:\Users\MyNameHere\AppData\Local\Programs\Python

Atom, for some reason here:
C:\Users\MyNameHere\AppData\Local\atom

There's more stuff right here:
C:\Users\MyNameHere\.atom\

Which appears to be where beautify installs itself:
C:\Users\MyNameHere\.atom\packages\atom-beautify

Why is all this stuff in unpredictable places? Why not, like all other applications, C:\Program Files?

And how do I solve the error?

**Comment by jayvdb** [comment]
You can probably solve the problem by adding `C:\Users\MyNameHere\AppData\Local\Programs\Python\Python36-32\Scripts` do your `PATH` environment variable.

Adding this to the `PATH` automatically is an option in the Python3.6 installer, and perhaps it wasnt enabled when you did the Python3.6 install.

> Why is all this stuff in unpredictable places?

Windows dictates `C:\Users\MyNameHere\AppData\Local\` is where many types of files should go, especially if they were installed by the user instead of being installed by a MSI.  That is part of why `pip` installs into that area.

**Comment by hhatto** [comment]
Thank you for using autopep8.
But, this is not autopep8's issue.

Thanks.

**Comment by toddfh** [comment]
'pip install --upgrade autopep8' fixed it for me.

**Comment by kdemenx** [comment]
Thanks, topic helped me with the same issue.

> You can probably solve the problem by adding C:\Users\MyNameHere\AppData\Local\Programs\Python\Python36-32\Scripts do your PATH environment variable.
