### ISSUE TITLE
pep8 error E501 is ignored completely 

### ISSUE THREAD

**Issue by nilakhya** [hhatto/autopep8#39]
steps  to reproduce : 
1. [xxxxx@localhost guest]# cat testpyt.py
   # ! /usr/bin/env python
   
   k = "this is a super long sentence to test the character limit of defining a variable that exceeds atleast 80 characters and see if this is taken care of autopep8 and what changes it does"
   print k
2. [xxxxx@localhost guest]# pep8 testpyt.py 
   testpyt.py:2:80: E501 line too long (188 > 79 characters)
3. [xxxxx@localhost guest]# autopep8 testpyt.py > testpyt2.py
4. [root@localhost guest]# pep8 testpyt2.py
   testpyt2.py:2:80: E501 line too long (188 > 79 characters)

version information : 

[root@localhost guest]# pep8 --version
1.3.3

[root@localhost guest]# autopep8 --version
autopep8: 0.8

**Comment by irving-ssk** [comment]
Folks, awesome tool doesn't have to be 100% awesome, but it better be close to 100% functional.
For example, if the size length is reached within a comment, breaking a comment in any place is better than doing nothing. Breaking at the last space before the margin (if it close enough) is better, but even the first alternative is better than nothing. No risk, no code broken.

**Comment by ddmee** [comment]
You could work out whether the string is a comment. For docstrings in python, we normally use triple quotes to surround the docstring. You know it's a docstring because the string isn't assigned to a variable and no operation is performed on the string.

So the solution is to:
1) Notice that the string is not operated on/not assigned to a variable. Therefore, it's a docstring or at least a string that no logic is performed on. Then just autostyle this to the line limit length.
2) IF it is a string to a variable or operated on, then use pythons implied continuation of strings. Break the string at the line limit and put the rest of the string the next line. python will automatically connect the two together. E.g.

This code is
`python
y = "this is a super long sentence to test the character limit of defining a variable that exceeds atleast 80 characters and see if this is taken care of autopep8 and what changes it does"
`
Equivalent to this code
`python
y = "this is a super long sentence to test the character limit of defining a variable"
      "that exceeds atleast 80 characters and see if this is taken care of autopep8"
      " and what changes it does"
`

**Comment by SamuelMarks** [comment]
Bump for @ddmee's suggestion

**Comment by dmartin-isp** [comment]
For me, the real problem was it didn't tell me what I was doing.  Flake8 is telling me my lines are too long, auopep8 is saying the lines are too long, but it does not ever tell me 'autopep8 cannot safely shorten this line, please do so by hand'.  Unless I'm just being silly and there's an

**Comment by amosnier** [comment]
I think what @dmartin-isp says makes sense, and I have an example. It seems that autopep8 (which is great, by the way) shortens

```
        src, obj, cmd = calc_object_cmd(src=src, src_dir=src_dir, build_dir=build_dir, compiler=compiler, defines=defines, std=std, includes=includes)
```

to

```
        src, obj, cmd = calc_object_cmd(src=src, src_dir=src_dir, build_dir=build_dir,
                                        compiler=compiler, defines=defines, std=std, includes=includes)
```
but not any further. That's a 103-long.

I can of course configure flake8 to accept that, but the shortening seems kind of arbitrary. Why not even shorter, if my configuration says so? Or am I missing something?
