### ISSUE TITLE
Spaces are wrongly added in type hints with default values.

### ISSUE THREAD

**Issue by exhuma** [hhatto/autopep8#473]
When having default arguments with type-hints, autopep8 will add spaces around the equals sign. But in that special case it should not do it. The following code should remain unchanged:

    def hello(name: str='John'): -> None:
        print('Hello %s' % name)

autopep8 falsely changes the first line to:

    def hello(name: str = 'John') -> None:

This is documented here: https://www.python.org/dev/peps/pep-0008/#other-recommendations

**Comment by Hanaasagi** [comment]
PEP 8 recommends this behavior.

```
When combining an argument annotation with a default value, however, do use spaces around the = sign:

Yes:

def munge(sep: AnyStr = None): ...
def munge(input: AnyStr, sep: AnyStr = None, limit=1000): ...

No:

def munge(input: AnyStr=None): ...
def munge(input: AnyStr, limit = 1000): ...
```

https://www.python.org/dev/peps/pep-0008/#other-recommendations

If I misunderstood your point, please correct me : )

**Comment by dreki** [comment]
The problem is that there seem to be two conflicting standards happening -- `E251` and `E252`. They seem to contradict each other.

For the purposes of linting and formatting in VS Code (the place I was running into this problem), you can fix this problem by installing `pycodestyle` (`pip3 install pycodestyle`)  and having VS Code use it in place of `pep8` (`"python.linting.pep8Path": "/usr/local/bin/pycodestyle"` in `settings.json`).
