### ISSUE TITLE
:= gets turned into : =, which is not correct syntax

### ISSUE THREAD

**Issue by ooa113y** [hhatto/autopep8#507]
## Python Code
```python

items = [{(s := y.split('='))[0]: s[1] for y in x} for x in items]
```

## Your Environment
* Python version: 3.8.0
* autopep8 version: 1.4.4
* Platform: Windows

**Comment by hhatto** [comment]
The release version of pycodestyle is not yet compatible with pep-572.
However, the latest master branch is already supported.

So the workaround is to install pycodestyle master.

```
$ pip install --upgrade git+https://github.com/PyCQA/pycodestyle.git@master
```

Thanks

**Comment by dzpt** [comment]
autopep8==1.5 still doesn't work ?

**Comment by hwalinga** [comment]
pycodestyle 2.6.0 released

https://github.com/PyCQA/pycodestyle/releases

And it works.

**Comment by sdstewar** [comment]
Just want to add a note in case anyone else runs into the same issue I did.  I use pyenv to manage multiple python versions on my dev machines and was running into this issue on a newer instance.  

Turns out that the pip install of autopep8 hardcodes the python path in the shebang part of the script.

> `#!/usr/bin/python3.6`

So while the script (and pycodestyle were at the latest version) autopep8 was installed using the python 3.6 env on the box and didn't pick up the setting 3.9.1 version that was setup later.   As such it was still correcting the syntax per 3.6.  

Reinstalling while being sure the python 3.9 env was coming up first in the path, via pyenv, fixed the issue.
> `#!/home/user/.pyenv/versions/3.9.1/bin/python3.9`
