### ISSUE TITLE
Autopep8 is not fixing F541 (f-string is missing placeholders)

### ISSUE THREAD

**Issue by forest-benchling** [hhatto/autopep8#554]
---
Is there a way to auto-fix Flake8's F541 (f-string is missing placeholders) error?

If not, would this be appropriate/easy to introduce? Thanks!

## Python Code
```python
f"foo"
```

## Command Line and Configuration
`.pep8`, `setup.cfg`, ...

Command Line
```shell
$ autopep8 -ri .
$ flake8 .
foo.py:1:1: F541 f-string is missing placeholders
```

## Your Environment
* Python version: 3.8
* autopep8 version: 1.5.3
* Platform: macOSX

**Comment by hhatto** [comment]
There's a similar issue in autoflake.
https://github.com/myint/autoflake/issues/67

Perhaps this fix will not be easy.
Because just pointing out that there are no placeholders is not enough to determine which variables to include.

If there is a better way, you could try throwing a pull-request to autoflake.

Thanks

**Comment by hhatto** [comment]
P.S.

> Perhaps this fix will not be easy.
Because just pointing out that there are no placeholders is not enough to determine which variables to include.

This might mean that you want to fix the following:

`f"foo"` -> `"foo"`

In that case, I feel the fix is easy.
